apiVersion: v1
kind: Config
clusters:
- name: teko-kubernetes
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3SGhjTk1qTXdOREU1TVRNeE9ERTBXaGNOTXpNd05ERTJNVE14T0RFMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFST1NhN215Sk9McHE1Nkh1YXdlYStVN3RwSVRTZVJ1U1RFMUd4SnFQQjkKOGthVnFkZ0k5OXVBUDZ3ZmxlRlExN0pTc0FOS3Y5UzdVSTZkdll0RFVNYU1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFhNkpBSUlOdUQvQUw2UGI5cmRCCnBXYWQvZFV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpjWFh0M1BqbEJGUjJrWGxIMFkvOElFd004dGtJd3MKR1UwT0oxVExQRElkQWlFQXVvaU5TbjN6T1ZiSmg0eFBiYUlUcDcvNTNFYThFTkRJekhmM05lMSt6L2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://webhost.internet-box.ch:6443
contexts:
- name: ogboi-teko9@teko-kubernetes
  context:
    cluster: teko-kubernetes
    namespace: teko9
    user: ogboi
users:
- name: ogboi
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlMyd2NqVVJjeTRqWnY3RmZOUlpHTHNUTDl0NTdaSDNabGllLXJNNWgwSk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZWtvOSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvZ2JvaS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvZ2JvaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjEzOTE4YzlmLWI3ZTItNGFiNC1hZDg3LWVmNjBiMGRjYTE5NiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp0ZWtvOTpvZ2JvaSJ9.k8WizqT2ssDJZYlG5j1gFpKnqxK_qKcs-nE6-Lid7fYAKLVJ0ntNJ7egRSj3mcG3uFpiznpa_ojVBSO0J0Dgf7YGNpb7acbUfP8TcC871KgJB7XbOqivzzlBxvZ6GbbYvEQKrwdHrMGwPx22T8W9p0mQMrtOgienft17RbC6izlOv26eQV9d3TWnGJeSI-pnpJdQecnqHks_HCh_RB0N_MV-hQQIIeOPhMvqDHLxPEPdSUaImEVjNpDwb6rs7a7AiVbWkmpSaksaSVJZY5Eo1mwo8GNdifX49OUjO1cyd-nnjPHcN8JsCtmIt6dNWRbLHpAmbSeYOhFJj8RDpBDtJA
current-context: ogboi-teko9@teko-kubernetes
